# Tox (http://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
requires =
    sphinx-scrapy @ git+https://github.com/scrapy/sphinx-scrapy.git@0.7.1
# pypy3 excluded due to https://github.com/kevin1024/vcrpy/issues/885
envlist = py{310,311,312}-{json,msgpack},docs

[testenv]
deps =
    -r tests/requirements.txt
    msgpack: -r tests/requirements-msgpack.txt
commands = py.test --cov=scrapinghub --cov-report=xml {posargs: scrapinghub tests}


[testenv:mypy]
basepython = python3
deps =
    mypy==2.3.1
    pytest==9.1.1
    responses==0.26.3
    types-mock==5.2.0.20260518
    types-requests==2.33.0.20260906
    types-six==1.17.0.20260724
commands =
    mypy {posargs: scrapinghub tests}
